config/routes.rb
Trial::Application.routes.draw do

  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up" 
  get "log_in" => "sessions#new", :as => "log_in" 
  get "books" => "users#show", :as => "books_page"
  root :to => "home#index"
  resources :users do
      resources :books
  end

  resources :sessions

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  attr_accessible :desc, :state, :title , :photo , :user
  has_attached_file :photo, :styles => { :small => "300x300>" },
                  :url  => "/assets/books/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/books/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/user.rb
class User < ActiveRecord::Base
    
    attr_accessible :email , :password, :password_confirmation
    has_many :books , :dependent => :destroy
    before_validation :downcase_email
    has_secure_password  
    validates_presence_of :password, :on => :create 
    validates :email, :presence => true, :uniqueness => true,
                      :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i} 
    validates :password,  :length => { :in => 6..20 , :too_short => "must have at least %{count} characters" , :too_long  => "must have at most %{count} characters"}

    private

    ## method to turn email into lower case characters
    def downcase_email
      self.email = self.email.downcase if self.email.present?
    end

end

app/controllers/application_controller.rb
    class ApplicationController < ActionController::Base  
      protect_from_forgery
        force_ssl    
      
      private  
      
      def current_user 
      #  @current_user=nil
      @current_user ||= User.find(session[:user_id]) if session[:user_id]  
      end  
      
       helper_method :current_user  
    end  

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
    def create
    @user = User.find(current_user.id)
    @book = @user.books.create(params[:book])
    redirect_to user_path(@user)
  end



 def destroy
    @user = User.find(current_user.id)
    @book = @user.books.find(params[:id])
    @book.destroy
    redirect_to user_path(@user)
  end

  def edit
     #   @book = Book.find(params[:id])
     #   @user = @book.user
     @user = User.find(current_user.id)
     @book = @user.books.find(params[:id])
end

def update
     @user = User.find(current_user.id)
     @book = @user.books.find(params[:id])
   # @book = Book.find(params[:id])
   # @user = @book.user
    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@user, :notice => 'book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end

end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
     def new  
      end  
      
     def create  
      user = User.find_by_email(params[:email])  
      if user && user.authenticate(params[:password])  
        session[:user_id] = user.id  
        redirect_to root_url, :notice => "Logged in! as #{current_user.email}"  
      else  

        flash.now.alert = "Invalid email or password"  
        render "new"
      end  
   end 

      def destroy  
        session[:user_id] = nil 
        redirect_to root_url, :notice => "Logged out!"  
      end  
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController  
    http_basic_authenticate_with :name => "nuha", :password => "butterfly", :only => :index
      def new  
        @user = User.new  
      end  
      
      def create  
        @user = User.new(params[:user])  
       
      respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: "Signed up!"}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    end 


    def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /books/new
  # GET /books/new.json
 

  # POST /books
  # POST /books.json

  # PUT /books/1
  # PUT /books/1.json
  def update
    @user = User.find(current_user.id)

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

      respond_to do |format|
      format.html { redirect_to @user, notice: 'user was deleted successfully' }
      format.json { head :no_content }
    end

   
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <h2>Edit Book:</h2>
<%= form_for([:user, @book]) do |f| %>
<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>

  <div class="field">
    <%= f.radio_button :state, 'read', :checked => true %> 
      <%= label :state_read, 'read' %>
      <%= f.radio_button :state, 'reading' %>
      <%= label :state_reading, 'reading' %>
      <%= f.radio_button :state, 'to_read' %>
      <%= label :state_to_read, 'to_read' %>
  </div>

    <%= f.file_field :photo %>

  <div class="actions">
    <%= f.submit %>
  </div>
  <%end%>


app/views/home/index.html.erb
THIS IS HOME ! :)
<% if current_user %>  
    Logged in as <%= current_user.email %>  
    <%= link_to "check your books", books_page_path %>  
  <% else %>  
    login to enjoy our site ! :D
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

  <body>

    <div class="page">
      <div class="header">
        <h1 id="logo"><%= link_to 'Maktabty', root_url ,:class => 'logo' %></h1> 
          <% if current_user %> 
            <ul> 
                 <li >Logged in as <%= current_user.email %></li>
                <li> <%= link_to "Book Shelf", books_page_path %>  </li>

                 <li ><%= link_to "Log out", log_out_path %></li>

            <ul>
            <% else %> 
            <ul> 
               <li ><%= link_to "Sign up", sign_up_path %></li>
               <li ><%= link_to "Log in", log_in_path %></li>
            </ul>
        <% end %>   
      </div>

      <div class="body">
          <% flash.each do |name, msg| %>  
          <div class="notice">
             <%= content_tag :div, msg, :id => "flash#{name}" %> 
          </div> 
          <% end %>
          <%= yield %>
      </div>

      <div class="footer">
                
        <p>&#169; Copyright &#169; 2012. Maktabty ...</p>
      </div>
    </div>




 
     
  


</body>
</html>

app/views/users/_newbook.html.erb
<h2>Add a book:</h2>
  <%= form_for([@user, @user.books.build]) do |f| %>
    <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>

  <div class="field">

      <%= f.radio_button :state, 'read', :checked => true %> 
      <%= label :state_read, 'read' %>
      <%= f.radio_button :state, 'reading' %>
      <%= label :state_reading, 'reading' %>
      <%= f.radio_button :state, 'to read' %>
      <%= label :state_to_read, 'to_read' %>

  </div>

    Book's Photo : <%= f.file_field :photo %>

  <div class="actions">
    <%= f.submit %>
  </div>

<%end%>

app/views/users/_showbooks.html.erb
<h2>Your BookShelf</h2>
<% @user.books.each do |book| %>
  <div class="book">
    <div class ="bookimg"><%= image_tag book.photo.url(:small) %></div> 
    <div class="bookinfo">
    <h3> Book's Name :    <%= book.title %> </h3>
    <p>Description : <%=book.desc%></p>
    <p>state : <%=book.state%></p>
     <%= link_to 'Edit', edit_user_book_path(@user, book) %> | 

   <%= link_to 'Destroy book', [book.user, book],
                 :confirm => 'Are you sure?',
                 :method => :delete %>
  </div>

 

</div>
<% end %>

app/views/users/index.html.erb

<h1>Listing users</h1>
<% unless @users.blank? %>

<table>
  <tr>
    <th>email</th>
    <th>password</th>
    <th> id </th>


    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
        <td><%= user.id %></td>


    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br/>


<%else%>
no users to display
<%end%>


<br />

app/views/users/new.html.erb
    <h1>Sign Up</h1>  
      
 <%= form_for @user do |f| %>  
      <% if @user.errors.any? %>  
        <div class="error_messages">  
          <h2>Form is invalid</h2>  
          <ul>  
            <% for message in @user.errors.full_messages %>  
              <li><%= message %></li>  
            <% end %>  
          </ul>  
        </div>  
      <% end %>  
      <div class="field">  
        <%= f.label :email %>  
        <%= f.text_field :email %>  
      </div>  
      <div class="field">  
        <%= f.label :password %>  
        <%= f.password_field :password %>  
      </div>  
      <div class="field">  
        <%= f.label :password_confirmation %>  
        <%= f.password_field :password_confirmation %>  
      </div>  
      <div class="actions"><%= f.submit %></div>  
    <% end %>  

app/views/users/show.html.erb
<%if @user.books.blank? %>
<p>you got no books :( have add your first book now : </p>

<%= render "users/newbook" %>


<%else%>

<%= render "users/showbooks" %>

<%= render "users/newbook" %>

<%end%>


<!--<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>-->

<!-- i add this 3shan lama 3mlt el if wa else ..ra7 mesh rady ye6l3 el footer :( -->